### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by hollamall** [chrisrollins65/cr_translate_mate#4]
Hi,

Can you please help with something? I want this extension to be more clever like to change the language based on ip address but more important.. i've seen another extension similar to yours except bulk translating : http://www.opencart.com/index.php?route=extension/extension/info&extension_id=21723&filter_search=translator&filter_download_id=42

In the above extension the programmer resolved the 2 million charters problem by  alternating with another account when 1 reached the limit. Can you make something like than in a update? The problem is that i have 33k products on my store and would cost me a lot to translate. 
The other plan above has this option but doesn't have the option to bulk upload. 
I've already purchased your extension but i can pay more if you help me with Microsoft accounts so it can use another one when is finished like again and again and again

Thanks

**Comment by chrisrollins65** [comment]
Hi hollamall,
1. This extension was only designed to aid in manual translating, so handling which language is used (for example, by IP address like you mentioned) is a completely separate issue that is out of the scope for this extension and should be handled in a different one. At the moment I don't have time to look into that.

2. The extension you linked to is meant to provide automatic translation. The problem with automatic translations is that they are often not adequate, since even the most advanced computer translation programs make translating mistakes. This extension was made precisely to be used by people who don't want to rely on automatic translations. That said, it could be interesting to see if automatic translations could be used when manually editing the translations to make things easier. I'll look into it, and also the possibility of performing automatic bulk translations.

Thanks for the suggestions!
