### ISSUE TITLE
Permission Denied!

### ISSUE THREAD

**Issue by siirtonurmi** [chrisrollins65/cr_translate_mate#9]
Hi, will translate mate have any new updates any time soon and is there perhaps some easy way to get it to run with 2.3.0.2? Now after installing it and when hitting "Edit" one gets an error window with text "You do not have permission to access this page, please refer to your system administrator."

Cheers, Juuso

**Comment by chrisrollins65** [comment]
Hello Juuso,
I no longer work with OpenCart, but I'll try to keep the translate mate extension up to date. I'll need some time to investigate the changes made since OpenCart 2.2 and update the extension accordingly.
Sincerely,
Chris Rollins
 

    On Wednesday, November 16, 2016 1:02 PM, siirtonurmi <notifications@github.com> wrote:
 

 Hi, will translate mate have any new updates any time soon and is there perhaps some easy way to get it to run with 2.3.0.2? Now after installing it and when hitting "Edit" one gets an error window with text "You do not have permission to access this page, please refer to your system administrator."Cheers, Juuso—

**Comment by thecotne** [comment]
there is workaround

in `oc_user_group` table find `Administrator` and edit `permission` json text
in `access` array add `extension/module/cr_translate_mate`

**Comment by siirtonurmi** [comment]
hmm, that seems to be in place already. Permission value ends "...,"extension\/module\/cr_translate_mate"]}". Could this problem be related to some language folder naming (copied from german language readme.txt):
"A.	up to version 2.1.0.2 English language folder was named: english
B.	from 2.2.x on the language folder is named: en-gb
C.	German was always de-DE from the beginning on"

**Comment by chrisrollins65** [comment]
Sorry, I haven't had time lately to look much into this. I somehow doubt that the naming of the language folder is the problem, but I need to look into it more. It's hectic because of holidays for me right now.

**Comment by AshandyChegevara** [comment]
ocstore 2.3.0.2,  everything is fine. Do not forget to turn on oermissions on files in settings of UserGroup permissons  opencart admin panel.

**Comment by chrisrollins65** [comment]
@siirtonurmi, did you ever find the solution to this or is it still a problem? If you're running OpenCart 3 now, try the newest version of this extension to see if it resolves your issue.
